#1. Total revenue generated:
SELECT SUM(oi.quantity * oi.sale_price) AS total_revenue
FROM order_items oi;

#2. Revenue generated by each store:
SELECT s.store_name, 
       SUM(oi.quantity * oi.sale_price) AS total_revenue
FROM stores s
JOIN orders o ON s.store_id = o.store_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.store_name;

#3. Revenue for each brand:
SELECT b.brand_name, 
       SUM(oi.quantity * oi.sale_price) AS total_revenue
FROM brands b
JOIN products p ON b.brand_id = p.brand_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY b.brand_name;

#4. Total revenue generated each year:
SELECT YEAR(o.order_date) AS order_year, 
       SUM(oi.quantity * oi.sale_price) AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY order_year
ORDER BY order_year;

#5. Total revenue generated each month:
SELECT YEAR(o.order_date) AS order_year, MONTH(o.order_date) AS order_month, 
       SUM(oi.quantity * oi.sale_price)  AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY order_year, order_month
ORDER BY order_year, order_month;

#6. Average revenue per order:
SELECT AVG(order_revenue) AS avg_revenue_per_order
FROM (
    SELECT o.order_id, SUM(oi.quantity * oi.sale_price)  AS order_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id
) subquery;

#7. Top 5 products contributing to total revenue:
SELECT p.product_name, 
       SUM(oi.quantity * oi.sale_price)  AS total_revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

#8. Average, maximum, and minimum discount rates:
SELECT AVG(discount_percentage) AS avg_discount_rate, 
       MAX(discount_percentage) AS max_discount_rate, 
       MIN(discount_percentage) AS min_discount_rate
FROM order_items;

#9. Average discount for each brand:
SELECT b.brand_name, AVG(oi.discount_percentage) AS avg_discount_rate
FROM brands b
JOIN products p ON b.brand_id = p.brand_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY b.brand_name;

#10. Orders with no discount applied:
SELECT COUNT(*) AS no_discount_orders
FROM order_items
WHERE discount_percentage = 0;

#11. Average discount for each store:
SELECT s.store_name, AVG(oi.discount_percentage) AS avg_discount_rate
FROM stores s
JOIN orders o ON s.store_id = o.store_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.store_name;

#12. Percentage of total revenue from discounted orders:
SELECT 
    ROUND(100 * (
        SELECT SUM(oi.quantity * oi.sale_price) 
        FROM order_items oi
        WHERE discount_percentage > 0
    ) / SUM(oi.quantity * oi.sale_price), 2) AS percentage_discounted_revenue
FROM order_items oi;

#13. Product category with the highest average discount per order:
SELECT c.category_name, AVG(oi.discount_percentage) AS avg_discount_rate
FROM categories c
JOIN products p ON c.category_id = p.category_id
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY avg_discount_rate DESC
LIMIT 1;

